SELECT
  t.OBJECTID,
  t.INTRID_SID,
  t.TENURE_STAGE,
  t.TENURE_STATUS,
  t.TENURE_TYPE,
  t.TENURE_SUBTYPE,
  t.TENURE_PURPOSE,
  t.TENURE_SUBPURPOSE,
  t.CROWN_LANDS_FILE,
  t.APPLICATION_TYPE_CDE,
  t.TENURE_DOCUMENT,
  t.TENURE_EXPIRY,
  t.TENURE_LOCATION,
  t.TENURE_LEGAL_DESCRIPTION,
  t.TENURE_AREA_DERIVATION,
  t.TENURE_AREA_IN_HECTARES,
  t.RESPONSIBLE_BUSINESS_UNIT,
  t.DISPOSITION_TRANSACTION_SID,
  t.CODE_CHR_STAGE,
  tenants.PRIMARY_CONTACT_YRN,
  tenants.TENANT_SID,
  tenants.INTERESTED_PARTY_SID,
  tenants.LOCATION_SID,
  tenants.SEPARATION_DAT,
  intpart.LEGAL_NAME,
  intpart.FIRST_NAME,
  intpart.LAST_NAME,
  intpart.WORK_AREA_CODE,
  intpart.WORK_EXTENSION_NUMBER,
  intpart.WORK_PHONE_NUMBER,
  t.SHAPE
FROM
  WHSE_TANTALIS.TA_TENANTS tenants
  INNER JOIN WHSE_TANTALIS.TA_INTERESTED_PARTIES intpart
  ON tenants.INTERESTED_PARTY_SID = intpart.INTERESTED_PARTY_SID
  RIGHT JOIN WHSE_TANTALIS.TA_CROWN_TENURES_SVW t
  ON t.DISPOSITION_TRANSACTION_SID = tenants.DISPOSITION_TRANSACTION_SID
WHERE
  tenants.PRIMARY_CONTACT_YRN = 'Y'
  AND update_query
ORDER BY
  t.INTRID_SID