SELECT 
  h.OBJECTID,
  h.TENURE_NUMBER_ID,
  h.TENURE_HIST_ID,
  tt.DESCRIPTION TENURE_TYPE_DESCRIPTION,  
  ts.DESCRIPTION TENURE_SUB_TYPE_DESCRIPTION,
  tc.DESCRIPTION MTA_TITLE_TYPE_CODE,
  t.ISSUE_DATE, 
  t.GOOD_TO_DATE, 
  t.MTA_TERMINATION_TYPE_CODE, 
  t.TENURE_NUMBER_ID_DEMISED_TO, 
  t.TERMINATION_DATE, 
  t.TERMINATION_COMMENTS, 
  t.PROTECTED_IND,
  h.REVISION_NUMBER,
  h.GEOMETRY 
FROM 
  MTA_SPATIAL.MTA_ACQUIRED_TENURE_HIST_POLY h
  inner join MTA.MTA_TENURE t
  on h.tenure_number_id = t.tenure_number_id
  inner join MTA.MTA_TENURE_TYPE_CODE tt
  on t.MTA_TENURE_TYPE_CODE = tt.MTA_TENURE_TYPE_CODE
  inner join MTA.MTA_TENURE_SUB_TYPE_CODE ts
  on t.MTA_TENURE_SUB_TYPE_CODE = ts.MTA_TENURE_SUB_TYPE_CODE
  inner join MTA.MTA_TITLE_TYPE_CODE tc
  on t.MTA_TITLE_TYPE_CODE = tc.MTA_TITLE_TYPE_CODE
WHERE
  update_query
ORDER BY
  h.TENURE_NUMBER_ID